import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      overflow: 'hidden',
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
      gap: 8,
    },
    cardHeaderIcon: {
      fontSize: 16,
      color: '#FF6B6B',
    },
    cardHeaderText: {
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
      color: '#FF6B6B',
    },
    editButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    editButtonIcon: {
      fontSize: 14,
    },
    editButtonText: {
      fontSize: 14,
      color: '#FF6B6B',
    },
    cardBody: {
      padding: 16,
    },
    userInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 20,
    },
    userAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FFE4E4',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    userAvatarText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FF6B6B',
    },
    cameraIconContainer: {
      position: 'absolute',
      bottom: -2,
      right: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#FF6B6B',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    cameraIcon: {
      fontSize: 10,
    },
    userName2: {
      fontSize: 18,
      fontWeight: '600',
      color: '#333333',
    },
    sectionLabel: {
      fontSize: 13,
      color: '#666666',
      marginBottom: 8,
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 20,
    },
    tag: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#FFE4E4',
      borderRadius: 16,
      gap: 6,
    },
    tagText: {
      fontSize: 13,
      color: '#FF6B6B',
      fontWeight: '500',
    },
    removeTagIcon: {
      fontSize: 16,
      color: '#FF6B6B',
      fontWeight: 'bold',
    },
    addConditionContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 20,
    },
    addConditionInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: '#333333',
      backgroundColor: '#FFFFFF',
    },
    addConditionButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#FF6B6B',
      alignItems: 'center',
      justifyContent: 'center',
    },
    addConditionButtonText: {
      fontSize: 20,
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    sectionTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#333333',
      marginBottom: 12,
    },
    detailItem: {
      marginBottom: 16,
    },
    detailLabel: {
      fontSize: 13,
      color: '#666666',
      marginBottom: 4,
    },
    detailValue: {
      fontSize: 15,
      color: '#333333',
    },
    detailInput: {
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 15,
      color: '#333333',
      backgroundColor: '#FFFFFF',
    },
    detailInputMultiline: {
      minHeight: 60,
      textAlignVertical: 'top',
    },
    heightWeightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    heightWeightInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 15,
      color: '#333333',
      backgroundColor: '#FFFFFF',
    },
    heightWeightSeparator: {
      fontSize: 15,
      color: '#666666',
    },
  });
