import { StyleSheet } from 'react-native';
import {
  surface,
  textPrimary,
  textSecondary,
  xs,
  sm,
  md,
  fontSm,
  fontMd,
  fontBase,
  fontLg,
  radiusSm,
  radiusMd,
} from '@/styles/tokens';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: md,
  },
  modalContainer: {
    backgroundColor: surface,
    borderRadius: radiusMd,
    width: '100%',
    maxWidth: 400,
    padding: md,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: xs,
  },
  modalTitle: {
    fontSize: fontLg,
    fontWeight: '700',
    color: textPrimary,
    flex: 1,
  },
  closeButton: {
    padding: xs,
    marginRight: -xs,
  },
  closeIcon: {
    fontSize: 20,
    color: textSecondary,
    fontWeight: '300',
  },
  modalDescription: {
    fontSize: fontSm,
    color: textSecondary,
    marginBottom: md,
    lineHeight: 18,
  },
  permissionsContainer: {
    marginBottom: md,
  },
  permissionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: sm,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  permissionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: sm,
  },
  permissionIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F9F9F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: sm,
  },
  permissionIcon: {
    fontSize: 16,
  },
  permissionInfo: {
    flex: 1,
  },
  permissionLabel: {
    fontSize: fontMd,
    fontWeight: '600',
    color: textPrimary,
    marginBottom: 2,
  },
  permissionDescription: {
    fontSize: fontSm,
    color: textSecondary,
    lineHeight: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: sm,
    marginTop: sm,
  },
  deleteButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: surface,
    borderWidth: 1,
    borderColor: '#FF6B6B',
    paddingVertical: sm,
    borderRadius: radiusSm,
  },
  deleteButtonIcon: {
    fontSize: 16,
    marginRight: 4,
  },
  deleteButtonText: {
    fontSize: fontBase,
    fontWeight: '600',
    color: '#FF6B6B',
  },
  saveButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B6B',
    paddingVertical: sm,
    borderRadius: radiusSm,
  },
  saveButtonText: {
    fontSize: fontBase,
    fontWeight: '700',
    color: surface,
  },
});
