import { StyleSheet } from 'react-native';
import {
  background,
  surface,
  border,
  textPrimary,
  textSecondary,
  accentPrimary,
  xs,
  sm,
  md,
  xl,
  fontSm,
  fontMd,
  fontBase,
  fontLg,
  fontXxxxl,
  radiusSm,
  headerButton,
} from '@/styles/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: sm,
    paddingTop: xl,
    paddingBottom: sm,
    backgroundColor: surface,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  backButton: {
    padding: xs,
    marginLeft: -xs,
  },
  backIcon: {
    fontSize: fontXxxxl,
    color: textPrimary,
    fontWeight: '300',
  },
  headerTitle: {
    fontSize: fontLg,
    fontWeight: '600',
    color: textPrimary,
  },
  headerRight: {
    width: headerButton,
  },
  scrollContent: {
    flex: 1,
  },
  contentWrapper: {
    paddingHorizontal: sm,
    paddingVertical: md,
  },
  noticeBox: {
    flexDirection: 'row',
    backgroundColor: '#E3F2FD',
    borderRadius: radiusSm,
    padding: sm,
    marginBottom: sm,
    alignItems: 'flex-start',
  },
  noticeIcon: {
    fontSize: 20,
    marginRight: xs,
    marginTop: 2,
  },
  noticeTextContainer: {
    flex: 1,
  },
  noticeTitle: {
    fontSize: fontMd,
    fontWeight: '600',
    color: '#1976D2',
    marginBottom: 4,
  },
  noticeText: {
    fontSize: fontSm,
    color: '#1565C0',
    lineHeight: 18,
  },
  section: {
    backgroundColor: surface,
    borderRadius: radiusSm,
    padding: sm,
    marginBottom: sm,
  },
  sectionTitle: {
    fontSize: fontBase,
    fontWeight: '700',
    color: textPrimary,
    marginBottom: md,
  },
  medicationCard: {
    backgroundColor: '#F5F5F5',
    borderRadius: radiusSm,
    padding: sm,
    marginBottom: sm,
  },
  medicationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: xs,
  },
  medicationName: {
    fontSize: fontMd,
    fontWeight: '600',
    color: textPrimary,
  },
  removeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButtonText: {
    fontSize: 18,
    color: '#999999',
    fontWeight: '600',
  },
  medicationDetail: {
    fontSize: fontSm,
    color: textSecondary,
    marginBottom: 2,
  },
  medicationTime: {
    fontSize: fontMd,
    color: textPrimary,
    marginTop: 4,
  },
  addMedicationContainer: {
    marginTop: sm,
  },
  medicationInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: border,
    borderRadius: radiusSm,
    paddingHorizontal: sm,
    paddingVertical: 12,
    fontSize: fontMd,
    color: textPrimary,
    marginBottom: xs,
  },
  addMedicationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: border,
    borderRadius: radiusSm,
    paddingVertical: 12,
    marginTop: xs,
  },
  addMedicationIcon: {
    fontSize: 18,
    color: textSecondary,
    marginRight: xs,
  },
  addMedicationText: {
    fontSize: fontMd,
    color: textSecondary,
    fontWeight: '500',
  },
  footer: {
    backgroundColor: surface,
    paddingHorizontal: sm,
    paddingVertical: sm,
    borderTopWidth: 1,
    borderTopColor: border,
  },
  saveButton: {
    backgroundColor: accentPrimary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: sm,
    borderRadius: radiusSm,
  },
  saveButtonIcon: {
    fontSize: 20,
    marginRight: xs,
  },
  saveButtonText: {
    fontSize: fontBase,
    fontWeight: '700',
    color: surface,
  },
});
