import type { Notification } from '@/_schema/notification';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: '心拍数異常',
    source: 'Apple Watch',
    timeAgo: '5分前',
    priority: 'high',
    status: 'unread',
    icon: '❤️',
    badge: '要対応',
  },
  {
    id: '2',
    title: '疲労度警告',
    source: 'ヘルスモニター',
    timeAgo: '12分前',
    priority: 'medium',
    status: 'unread',
    icon: '❤️',
  },
  {
    id: '3',
    title: '休憩時間です',
    source: '休憩スケジューラー',
    timeAgo: '16分前',
    priority: 'low',
    status: 'unread',
    icon: '🕐',
  },
  {
    id: '4',
    title: '活動量過多',
    source: 'アクティビティトラッカー',
    timeAgo: '25分前',
    priority: 'medium',
    status: 'unread',
    icon: '⚡',
  },
  {
    id: '5',
    title: 'トイレリマインダー',
    source: 'スケジュール',
    timeAgo: '35分前',
    priority: 'low',
    status: 'read',
    icon: '🕐',
  },
  {
    id: '6',
    title: '服薬時間',
    source: 'スケジュール',
    timeAgo: '1時間前',
    priority: 'high',
    status: 'read',
    icon: '💊',
    badge: '完了',
  },
  {
    id: '7',
    title: '水分補給のリマインド',
    source: 'ヘルスモニター',
    timeAgo: '2時間前',
    priority: 'low',
    status: 'read',
    icon: '💧',
  },
];
